const NotFound = () => {
  return (
    <div className="flex min-h-[70vh] w-full flex-col items-center justify-center gap-12">
      <div className="flex flex-col items-center justify-center text-center">
        <p className="text-3xl font-semibold text-primary">
          Nothing to see here
        </p>
        <p className="text-base font-normal text-secondary">
          So here is a random image generated by{" "}
          <span className="text-presentiq">Creative AI</span>
        </p>
      </div>
    </div>
  );
};

export default NotFound;
